### ISSUE TITLE
Suggestion: Is there a way for you to make it so the script can to avoid back2back advertising?

### ISSUE THREAD

**Issue by paul38752** [XtramCZ/auto-advertise-js#10]
I keep getting warned or muted on servers for back-to-back advertising. I know I can just raise the cooldown to something higher, but I don't want to be advertising too infrequently. There should be a feature where you can set the minimum amount of messages posted before you post.
Example:

default:
  token: 'put your token here'
  interval: '60' # How much minutes to wait before sending another batch of messages (Default: 60)
  messages: '2' # how many messages other people post before you repost yours (Do this to avoid double posting)
  debug_mode: 'false' # If set to true, you will get a log in the console every time a message is sent (Default: false)
  channels: # Channels where to send the message
    - 'xxxxxxxxxxxxxxxxxxx'
    - 'xxxxxxxxxxxxxxxxxxx' # etc

if this is not possible you could alternatively make it an option to automatically delete previous ads although some servers might catch on this and detect you're using self bots and ban you

**Comment by XtramCZ** [comment]
Hi, thanks for your suggestion, I'll try to come up with something. 

I can also add "minimum interval" and "maximum interval" between posting, so your messages look more legit.

**Comment by XtramCZ** [comment]
However, I have to warn you that checking messages in the channel in order to prevent double posting will result in more delays between posting in different channels, and that means the tool will be slower

**Comment by paul38752** [comment]
@XtramCZ ive already done something like that to randomize time in the index.js file to avoid self bot detection it would be a good idea to implement it though
var random = (Math.random() * 6 - 2) + 2;
setTimeout(sendMessage, config.interval * 60000 * random)

**Comment by paul38752** [comment]
the delay in checking messages before posting would be fine since i have this script running all day plus i can set interval lower to prevent this

**Comment by paul38752** [comment]
you can make this optional if some people are not ok with the delay

**Comment by paul38752** [comment]
Another feature I would like to suggest is to optionally allow the script to wait the exact interval before you run it. For example, I have multiple scripts running for different accounts on different servers, and if I restart my computer, I have to run them manually again, but if I run them all at once, it leads to spam, and the index.js file automatically starts without waiting the interval isn't in use until after you run it for the first time. I risk accidental spamming, which is getting me warnings on servers. and I've already been banned from a few.

**Comment by XtramCZ** [comment]
sure

**Comment by XtramCZ** [comment]
I uploaded a new version with your suggestions. Please try it and tell me if something is not right

**Comment by paul38752** [comment]
it works for a while then i get this

        'Authorization',
          'my token'
        ],
        'user-agent': [ 'User-Agent', 'axios/1.3.5' ],
        'content-length': [ 'Content-Length', '26' ],
        'accept-encoding': [ 'Accept-Encoding', 'gzip, compress, deflate, br' ],
        host: [ 'Host', 'discord.com' ]
      },
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      code: 20016,
      global: false,
      message: 'This action cannot be performed due to slowmode rate limit',
      retry_after: 3273.511
    }
  }
}

**Comment by XtramCZ** [comment]
Fixed.

**Comment by paul38752** [comment]
thanks it works but one minor suggestion i'd like to add is that you add a randomize interval to avoid_spam: variable like i can set it to pick a value between 2-5 to make my messages look more legit.

**Comment by XtramCZ** [comment]
that's what "minimal_interval" and "maximum_interval" should do

**Comment by XtramCZ** [comment]
Okay, I will, but for now I am closing this thread. Thanks for your suggestions
