### ISSUE TITLE
new version does not work

### ISSUE THREAD

**Issue by paul38752** [XtramCZ/auto-advertise-js#11]
the old version a that did not have the randomize minimum messages feature does work but this one does not and is double posting

**Comment by paul38752** [comment]
another issue is this is both with new and old version once it reaches an invalid channel example being a channel that was deleted or a server i been banned from it stops completely

**Comment by XtramCZ** [comment]
any errors?

**Comment by XtramCZ** [comment]
Crashing fixed

**Comment by XtramCZ** [comment]
btw the minimum and maximum messages work for me, try enabling debug mode

**Comment by XtramCZ** [comment]
It's kinda dumb tho, because it is choosing a new number every time. If you want it to choose one number and wait until the messages are higher than the number in that channel, I can do it but probably tomorrow. For now you can use the old version

**Comment by paul38752** [comment]
it works now
