### ISSUE TITLE
is it possible to use a bot for slash commands?

### ISSUE THREAD

**Issue by paul38752** [XtramCZ/auto-advertise-js#12]
for example automatic bumping with disboard and other listing bots

**Comment by XtramCZ** [comment]
I can try to implement it but I don't know if it would work. Btw IIRC disboard still supports message commands

**Comment by paul38752** [comment]
they don't anymore !d bump doesn't do anything

**Comment by XtramCZ** [comment]
I couldn't make it work, sorry
