### ISSUE TITLE
Is there any way to have a few seconds delay between each message?

### ISSUE THREAD

**Issue by Kephronic** [XtramCZ/auto-advertise-js#13]
Hi, i just tested the new version what you uploaded, is amazing tbh
But there's a thing what have me a little bit scared, the tool is working great but, when the tool starts sending messages it does instantly, like all the messages sent without any delay time between each ones, isn't like before you can change one thing in the code to change the delay time between the messages, i don't know if i'm explaining really well, i hope i was explained the matter properly
I'm just asking if there's any way to set or have a delay time between any message sent in a server, of like 2 - 3 seconds because i think Discord can detect sus things if someone sends more than 100 messages in different servers & channels in less than a minute, it could be really cool if the tool can have it randomized if you made that option, for example: i'm sending a message in 3 servers and i just set a delay between messages of minimum 2 seconds and maximum 5 seconds (this is just a example, i don't know if i'm explaining my point really well y'know), the first one is without the delay time, then the second message can be sent randomly between 2 or 5 seconds after the first, let's say in this example it got sent 4 seconds after the first one, then the third one idk, is sent 2 seconds after the second one
I hope i just get understand, i hope that could be added because i think is great and can be better, safer and really hard to detect by Discord

**Comment by XtramCZ** [comment]
Hi, thanks for the suggestion. I added it to the code, please test it and tell me if something is not working.

**Comment by Kephronic** [comment]
I just tested it and is working perfect, thanks for adding it!
Btw, there's a bug if you have enabled the option of avoid spam
If you try to send a message in a channel without any message previously it pop ups this error and the tool crashes

C:\Users\Administrator\Downloads\auto-advertise-js-main\index.js:38
    if(response.data[i].author.id == user_id){
                        ^

TypeError: Cannot read properties of undefined (reading 'author')
    at checkDoublePosting (C:\Users\Administrator\Downloads\auto-advertise-js-main\index.js:38:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendToChannel (C:\Users\Administrator\Downloads\auto-advertise-js-main\index.js:49:20)

Node.js v19.8.1

C:\Users\Administrator\Downloads\auto-advertise-js-main>pause
Press any key to continue . . .

**Comment by Kephronic** [comment]
And there's another bug! 
For any reason after using the tool for a few moments it just crash and sent this error code, is more longest but i can't send it completely, i don't know why

C:\Users\Administrator\Downloads\auto-advertise-js-main\node_modules\axios\dist\node\axios.cjs:1900
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 403
    at settle (C:\Users\Administrator\Downloads\auto-advertise-js-main\node_modules\axios\dist\node\axios.cjs:1900:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Administrator\Downloads\auto-advertise-js-main\node_modules\axios\dist\node\axios.cjs:2952:11)
    at IncomingMessage.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: [Function: FormData] {
        LINE_BREAK: '\r\n',
        DEFAULT_CONTENT_TYPE: 'application/octet-stream'
      },
      Blob: [class Blob]
    },

**Comment by XtramCZ** [comment]
Error 403 could mean that your token changed, or you don't have access to a channel you're trying to post in. Otherwise, the errors are handled so I don't know what could be causing this
