### ISSUE TITLE
Randomize messages

### ISSUE THREAD

**Issue by lfgan8** [XtramCZ/auto-advertise-js#15]
Can you make a feature where you can put multiple messages into the messages.txt file and it randomly chooses one instead of sending the same message over and over again? Also Wick bot has a feature that makes it so if you send the same message multiple times no matter the interval it will time you out

**Comment by XtramCZ** [comment]
Hello, thanks for your suggestion. I have implemented it into the code, please test it and let me know if something breaks :]
