### ISSUE TITLE
Token Invalid

### ISSUE THREAD

**Issue by frDESI** [XtramCZ/auto-advertise-js#19]
whenever i tryna run the code on repl it say "Token Is Invalid" i checked and changed token many times to work it. but still its showing same error
![image](https://github.com/XtramCZ/auto-advertise-js/assets/136969474/bf08fc39-fc06-4f6b-8625-269d817b0822)

**Comment by XtramCZ** [comment]
Hi. Before I try to replicate this, do you have 2FA on? That could mess with the token

**Comment by frDESI** [comment]
> Hi. Before I try to replicate this, do you have 2FA on? That could mess with the token

Nope, 2FA is off

**Comment by XtramCZ** [comment]
Could not replicate, please check your token/config again and check if the script works locally, it could be a replit issue. 
I'm closing this issue as not planned for now.
