### ISSUE TITLE
script stops completely when i reach a channel where i can't post due to cooldown

### ISSUE THREAD

**Issue by paul38752** [XtramCZ/auto-advertise-js#4]
For example, if I want to post my server ad in every channel on a server once an hour, let's say they're 30s, 1m, 30, 1h, 6h, community servers, meme servers, gaming servers,
Once I get to the 6h channel, since the script runs once an hour, the entire script stops working, and it won't post in any other channels, even the ones where the cooldown is less than 1 hour. Make it so the script continues posting in other channels even when it reaches one channel where the cooldown is too high. I hope my explanation makes sense.

**Comment by XtramCZ** [comment]
Hello, please try the new version and let me know if the fix works.

**Comment by paul38752** [comment]
works now
