### ISSUE TITLE
suggestion can you make it so you can set different channels to have different cooldowns

### ISSUE THREAD

**Issue by paul38752** [XtramCZ/auto-advertise-js#5]
for example some servers are less active so if i were to post once an hour i would be spamming and i could get muted some servers with a lot more members are more active so i want to be able to post more frequently

**Comment by XtramCZ** [comment]
Thanks for the suggestion, however right now I am focused more on making the tool work than adding features. Maybe in the future, or maybe someone might do it themselves and make a pull request.
