### ISSUE TITLE
I don't know how to installed the tool help plis!

### ISSUE THREAD

**Issue by CiriaX** [XtramCZ/auto-advertise-js#8]
hi! so I'm new and i've looking for a tool just like this to be used in markets to promote my products but I'm very new into this and I don't know how to installed this, so I would thanks a lot if you can explained to me. Thank you very much.
![image](https://user-images.githubusercontent.com/103872620/229405032-250bce7d-485d-4d3c-aeae-96096bfb81e4.png)

**Comment by CiriaX** [comment]
Umm forget about the problem of the installation now I have another problem that I can't fix
![image](https://user-images.githubusercontent.com/103872620/229411401-f3c344cb-6109-459c-88e3-6268f515d7cc.png)

**Comment by XtramCZ** [comment]
Hello, i uploaded a new fix, please test it.

**Comment by CiriaX** [comment]
> Hello, i uploaded a new fix, please test it.

So the thing is for me that it was not working with only one channel but when I put 2 different channels it started working perfectly. Btw a suggestion can you make it that you can send specific messages for certain channel and with a specific timer that's all I wanted to say thanks for this selfbot it helps me a lot in my black market.

**Comment by XtramCZ** [comment]
I don't know why it doesn't work with only one channel, did you get any errors? Anyways, someone already suggested a separate timer for each channel but right now I focus more on making the tool work than adding more features.

**Comment by CiriaX** [comment]
> I don't know why it doesn't work with only one channel, did you get any errors? Anyways, someone already suggested a separate timer for each channel but right now I focus more on making the tool work than adding more features.

Yeah I tried the new one, but it only works with more than 1 channel, I don't know why but the tool is amazing, but I do believe that separate timer for each channel will be a great funtion that will definitly make this tool a 100% complete, but its up to you take your time to refine what you have now and when you can do new features if you want. I'll be waiting thanks for the tool!

**Comment by XtramCZ** [comment]
Okay, thanks for the support :)
